# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeployDoctor < Formula
  desc "Diagnose container deploy readiness"
  homepage "https://github.com/navig-me/deploy-doctor"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.5/deploy-doctor_0.1.5_darwin_amd64.tar.gz"
      sha256 "378872bb91b9921cf41ee546ed95d8ed4088f8af6340ddc3839a73fa28742254"

      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.5/deploy-doctor_0.1.5_darwin_arm64.tar.gz"
      sha256 "4d1164c2849ad17227f0bf71eb14f45afddde76b4e2361de8622e818c38bf843"

      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.5/deploy-doctor_0.1.5_linux_amd64.tar.gz"
      sha256 "c0562b461c23a73e07fe8adaf9e2cc40a669ad3f70c08453baf098f02e3fcabb"
      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.5/deploy-doctor_0.1.5_linux_arm64.tar.gz"
      sha256 "891816173ccdbbaf94e33aa0c73bce0647041c03f1bbc6e1900eef9275676d41"
      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
  end

  test do
    system "#{bin}/deploy-doctor", "version"
  end
end
