# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeployDoctor < Formula
  desc "Diagnose container deploy readiness"
  homepage "https://github.com/navig-me/deploy-doctor"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.4/deploy-doctor_0.1.4_darwin_amd64.tar.gz"
      sha256 "3989cc5ec784fdb354b2fee131dab1f4a33bdc9d68bffbdf28558a103c07a2bb"

      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.4/deploy-doctor_0.1.4_darwin_arm64.tar.gz"
      sha256 "2ed066b5472eb5d1b465e483e4188ae6cfe3645e732ce624df4187139ad33481"

      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.4/deploy-doctor_0.1.4_linux_amd64.tar.gz"
      sha256 "68ea4ea3fd5457b68ae15f41aa50391374eea236d8b17ad3cfebf8a5c5453887"
      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/navig-me/deploy-doctor/releases/download/v0.1.4/deploy-doctor_0.1.4_linux_arm64.tar.gz"
      sha256 "ae310176f27ffed9767adcc436a44cfcaa6b19bad9df0bac2bf2e3f83b973109"
      define_method(:install) do
        bin.install "deploy-doctor"
      end
    end
  end

  test do
    system "#{bin}/deploy-doctor", "version"
  end
end
